apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-customer
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ace/create-customer/environments/overlays/dev
    repoURL: https://github.com/mfarhanSystemsltd/gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
