apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ace/create-customer/environments/base
    repoURL: https://github.com/mfarhanSystemsltd/gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
